export const SEND_MSG = "SEND_MSG"
export const SEND_MSG_FAILED = "SEND_MSG_FAILED"
export const DOWNLOAD_MSGS = "DOWNLOAD_MSGS"
export const DOWNLOAD_MSGS_FAILED = "DOWNLOAD_MSGS_FAILED"
export const SET_MSGS = "SET_MSGS"
export const MY_MSG_RECEIVED = "MY_MSG_RECEIVED"
export const MY_MSG_SEEN = "MY_MSG_SEEN"
export const THEIR_MSG_RECEIVED = "THEIR_MSG_RECEIVED"
export const THEIR_MSG_SEEN = "THEIR_MSG_SEEN"


export const FIND_USER_INIT = "FIND_USER_INIT"
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS"
export const FIND_USER_FAIL = "FIND_USER_FAIL"
 

export const ADD_USER_INIT = "ADD_USER_INIT"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"